/*
 * This source file was generated by the Gradle 'init' task
 */
package io.cwm.astral;

import io.cwm.engine.logic.GameManager;
import io.cwm.engine.logic.math.Vec2;
import io.cwm.engine.rendering.ImagePanel;
import io.cwm.engine.rendering.Sprite;
import io.cwm.engine.rendering.SpriteSheet;
import io.cwm.engine.resources.ResourceLocator;

public class Astral {
    public static final String NAME = "Astral";

    public static void main(String[] args) {
        Astral.startGame();
    }

    public static void startGame() {
        //setup
        GameManager.addObject(
                new ImagePanel(
                        new ResourceLocator("assets/textres/img.png")
                )
        );

        GameManager.addObject(
                new Sprite(
                        new SpriteSheet(
                                new ResourceLocator("assets/textures/img.png"),
                                new Vec2(100, 541)
                        ),
                        10,
                        new Vec2(200, 100)
                )
        );

        Sprite slimeSpawn = new Sprite(
                new SpriteSheet(
                        new ResourceLocator("assets/textures/slime_spawn.png"),
                        new Vec2(100, 100)
                ),
                10,
                new Vec2(400, 200)
        );

        GameManager.addObject(slimeSpawn);

        TestingSlime test = new TestingSlime(new Vec2(600, 200));
        GameManager.addObject(test);

        GameManager.startLoop(60);
    }
}
