/*
 * This source file was generated by the Gradle 'init' task
 */
package io.cwm.astral;

import io.cwm.engine.logic.GameManager;
import io.cwm.engine.rendering.ImagePanel;
import io.cwm.engine.resources.ResourceLocator;

public class Astral {
    public static final String NAME = "Astral";

    public static void main(String[] args) {
        Astral.startGame();
    }

    public static void startGame() {
        //setup
        GameManager.addObject(new ImagePanel(new ResourceLocator("assets/textures/img.png", true)));
        GameManager.startLoop(60);
    }
}
